version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: note_forge
      MYSQL_USER: noteforge_user
      MYSQL_PASSWORD: strongpassword123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  api:
    build:
      context: ./note-forge-api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    command: ["npm", "start"]

  ui:
    build: ./note-forge-ui
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  db_data:
